version: '3.9'

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=root2
      - MYSQL_DATABASE=citizix_db